### ISSUE TITLE
ensenso_node: depends on unreleased / non-existing pkgs

### ISSUE THREAD

**Issue by gavanderhoorn** [delftrobotics/dr_ensenso#1]
It seems there are some dependencies that are declared by `dr_ensenso_node` that cannot be resolved / are not available (from: [dr_ensenso_node/package.xml](https://github.com/delftrobotics/dr_ensenso/blob/8d92fa1492debb37f63aeddd4e8dfd3d2e9ec789/dr_ensenso_node/package.xml#L19-L21)):

```xml
  <depend>dr_msgs</depend>
  <depend>dr_ros</depend>
  <depend>dr_thread</depend>
```

I haven't checked whether they are actually used.

**Comment by de-vri-es** [comment]
All of them are in use. `dr_msgs` for `GetPose.srv`, `dr_ros` for the service client wrappers used by the calibration tool and `dr_thread` to save recorded data in the background to avoid blocking service call handlers.

I'll discuss if we can publish those packages on github or if we'll remove the dependencies.

**Comment by de-vri-es** [comment]
Actually, the service client wrappers aren't used. The ensenso node inherits from `dr::Node` from `dr_ros` though.

**Comment by de-vri-es** [comment]
Never mind my previous comments. I removed the dependencies on unreleased packages. The only functional change should be that recorded data is no longer dumped in a background thread, so the service handlers are blocked until that finishes.

I'm not sure if the node dumps the recorded data by default. It can be turned off at any rate.

Can you verify that you can compile the package? There is a dependency on `dr_param` now (instead of `dr_ros`), but that one is released.

**Comment by de-vri-es** [comment]
I'll assume the issue fixed. If you have further problems you can re-open the issue (or leave a comment if github doesn't allow you to).
